---
- hosts: pi_group
  become: true

  vars_prompt:
    - name: "cloudflared_tunnel_id"
      prompt: "Enter your Cloudflared Tunnel ID (without .json) or press Enter to skip Cloudflared setup"
      private: no
      default: ""

  pre_tasks:
    - name: Set cloudflared variables
      set_fact:
        cloudflared_enabled: "{{ cloudflared_tunnel_id | length > 0 }}"

  roles:
    - common
    - docker
    - ssh
    - cloudflared
    - n8n

  post_tasks:
    - name: "PAUSE: Manual steps for Cloudflared setup (if tunnel ID provided)"
      pause:
        prompt: |
          "{% if cloudflared_enabled %}Manual steps required!\n\n1. Go to the Cloudflare dashboard and set up CNAME records:\n   - n8n.konfortes.uk -> {{ cloudflared_tunnel_id }}.cfargotunnel.com\n   - ssh.konfortes.uk -> {{ cloudflared_tunnel_id }}.cfargotunnel.com\n\n2. Set up SSH keys for secure access:\n   - Generate SSH key pair: ssh-keygen -t ed25519 -C 'your-email@example.com'\n   - Copy public key to Pi: ssh-copy-id pi@ssh.konfortes.uk\n\n3. To SSH to your Pi, use:\n   - ssh pi@ssh.konfortes.uk\n\nWhen you are done, press Enter to finish the playbook.{% else %}Cloudflared setup skipped. Press Enter to finish the playbook.{% endif %}\n\nPress Enter to continue..."
      when: cloudflared_enabled 