---
# Common role tasks
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: common

- name: Install required apt packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
  tags: common 